# Generated by Django 5.2.5 on 2026-08-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
