# Generated by Django 5.2.5 on 2026-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_visitor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Karta'), ('MOBILE', 'Mobile'), ('TRANSFER', "Bank o'tkazish")], default='CASH', max_length=10),
        ),
    ]
