# Generated by Django 5.2.5 on 2026-08-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('UZS', "UZS (So'm)"), ('USD', 'USD ($)')], default='UZS', max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
