# Generated by Django 5.2.5 on 2026-09-04 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_multitenancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Oxirgi marta tahrirlangan sana (faqat tahrirlansa)', null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Oxirgi marta tahrirlangan sana (faqat tahrirlansa)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
